In [4]:
import pandas as pd
from unidecode import unidecode

In [6]:
# Reads the dataset file: csv.
# Read translated xlsx
df = pd.read_csv("reviews_translated_csv.csv")

In [8]:
df.head()

,name,country,room_type,nr_nights,date,traveler_type,title_review,pos_review,neg_review,score,pos_review_en,neg_review_en,title_review_en
0,Christina,Belgium,Comfort Double Room,3 nights ·,January 2025,Family,Exceptional,"Room was spacious, clean and with good amenities",NaN,Scored 10,"Room was spacious, clean and with good amenities",NaN,Exceptional
1,Helen,United Kingdom,Comfort Single Room,2 nights ·,March 2025,Solo traveller,Well placed hotel with great facilities,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Scored 9.0,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Well placed hotel with great facilities
2,Irene,United Kingdom,Comfort King Room,2 nights ·,March 2025,Couple,Very clean with professional staff and very go...,Staff is very friendly and extremely professio...,Nothing,Scored 9.0,Staff is very friendly and extremely professio...,Nothing,Very clean with professional staff and very go...
3,Andrea,Hungary,Plus Comfort Suite,4 nights ·,February 2025,Family,"Elegant, good hotel in the center",We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...",Scored 9.0,We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...","Elegant, good hotel in the center"
4,Anjali,Canada,Comfort Family Room,2 nights ·,February 2025,Family,Good location and nice hotel with spacious units.,Location and size of the unit. Comfortable for...,NaN,Scored 8.0,Location and size of the unit. Comfortable for...,NaN,Good location and nice hotel with spacious units.

In [10]:
# 1) Extrair apenas o número de noites
df['nr_nights'] = df['nr_nights'].str.extract(r'(\d+)')
df['nr_nights'] = pd.to_numeric(df['nr_nights'])

# 2) Separar mês e ano na coluna date
df[['month', 'year']] = df['date'].str.extract(r'(\w+) (\d{4})')
df['year'] = pd.to_numeric(df['year'])

# 3) Extrair apenas o número da coluna score (pode ser inteiro ou decimal)
df['score'] = df['score'].str.extract(r'(\d+\.?\d*)').astype(float)

df['country'].fillna('Unknown', inplace=True)

In [12]:
df[['pos_review', 'neg_review', 'pos_review_en', 'neg_review_en']] = df[[
    'pos_review', 'neg_review', 'pos_review_en', 'neg_review_en']].fillna('No review')

# Ter "Nothing" na review quer dizer que a pessoa escreveu "Nothing", quando temos "No review", foi o código a corrigir os NaN.

In [14]:
col_order = [
    'name', 'country', 'room_type', 'traveler_type', 'nr_nights', 'date', 'year', 'month', 'score',
    'title_review', 'title_review_en', 'pos_review', 'pos_review_en', 'neg_review', 'neg_review_en']
df = df[col_order]
df.head(2)

,name,country,room_type,traveler_type,nr_nights,date,year,month,score,title_review,title_review_en,pos_review,pos_review_en,neg_review,neg_review_en
0,Christina,Belgium,Comfort Double Room,Family,3,January 2025,2025,January,10.0,Exceptional,Exceptional,"Room was spacious, clean and with good amenities","Room was spacious, clean and with good amenities",No review,No review
1,Helen,United Kingdom,Comfort Single Room,Solo traveller,2,March 2025,2025,March,9.0,Well placed hotel with great facilities,Well placed hotel with great facilities,In good location for exploring Porto… approx 2...,In good location for exploring Porto… approx 2...,Can’t think of any improvement,Can’t think of any improvement

In [16]:
def clean_text(text):
    if isinstance(text, str):
        text = unidecode(text)  # Remove acentos
        text = text.replace('\n', ' ')  # Substituir quebras de linha
        text = text.strip()  # Remover espaços extra
    return text

# Aplicar a limpeza nas colunas de texto
cols_to_clean = ['title_review', 'pos_review', 'neg_review', 'title_review_en', 'pos_review_en', 'neg_review_en']
df[cols_to_clean] = df[cols_to_clean].applymap(clean_text)

In [18]:
for col in df.columns:
    print(f"Valores únicos na coluna '{col}':\n", df[col].unique(), "\n")

Valores únicos na coluna 'name':
 ['Christina' 'Helen' 'Irene' ... 'Shameem' 'Keenosz' 'Karlheinz']

Valores únicos na coluna 'country':
 ['Belgium' 'United Kingdom' 'Hungary' 'Canada' 'United States' 'Ireland'
 'Portugal' 'Australia' 'France' 'Saudi Arabia' 'United Arab Emirates'
 'Turkey' 'Malta' 'Germany' 'Netherlands' 'Kuwait' 'Switzerland' 'Sweden'
 'Lithuania' 'Spain' 'Costa Rica' 'Georgia' 'Mexico' 'New Zealand'
 'Brazil' 'Israel' 'Mauritius' 'Bosnia and Herzegovina' 'Cyprus' 'Greece'
 'Bonaire St Eustatius and Saba' 'Iceland' 'Romania' 'Austria'
 'Luxembourg' 'Chile' 'Jersey' 'South Africa' 'Singapore' 'Italy'
 'Venezuela' 'Gibraltar' 'Slovakia' 'Serbia' 'Poland' 'Egypt' 'Qatar'
 'Dominican Republic' 'Latvia' 'Denmark' 'Unknown' 'Azerbaijan' 'Armenia'
 'Philippines' 'Malaysia' 'India' 'Pakistan' 'Czech Republic' 'Jordan'
 'Croatia' 'Finland' 'Colombia' 'Hong Kong' 'Indonesia' 'Morocco'
 'Estonia' 'Puerto Rico' 'Reunion' 'Tunisia' 'Argentina' 'Ukraine'
 'Angola' 'Guadeloupe' 'Mozambique' 'China' 'Monaco' 'Russia' 'Uruguay'
 'Norway' 'Saint Barthelemy' 'Honduras' 'Japan' 'South Korea' 'Peru'
 'Kazakhstan' 'French Polynesia' 'San Marino' 'Ecuador' 'Algeria'
 'Slovenia' 'Lebanon' 'Thailand' 'Guatemala' 'Vietnam' 'Albania' 'Moldova'
 'Andorra' 'Bulgaria' 'Oman' 'Taiwan' 'Montenegro']

Valores únicos na coluna 'room_type':
 ['Comfort Double Room' 'Comfort Single Room' 'Comfort King Room'
 'Plus Comfort Suite' 'Comfort Family Room' 'Comfort Suite'
 'Comfort King Double Room with Romantic Package' 'Deluxe Panoramic Suite'
 'Suite Premium Deluxe' 'Comfort Family Room Plus' 'Comfort Twin Room'
 'Double Room - Disability Access']

Valores únicos na coluna 'traveler_type':
 ['Family' 'Solo traveller' 'Couple' 'Group']

Valores únicos na coluna 'nr_nights':
 [ 3  2  4  1  7  5  8  6  9 13 10 12 15 17 14]

Valores únicos na coluna 'date':
 ['January 2025' 'March 2025' 'February 2025' 'October 2024'
 'December 2024' 'November 2024' 'September 2024' 'August 2024'
 'July 2024' 'June 2024' 'May 2024' 'March 2024' 'April 2024'
 'February 2024' 'January 2024' 'December 2023' 'November 2023'
 'October 2023' 'September 2023' 'August 2023' 'July 2023' 'May 2023'
 'June 2023' 'March 2023' 'April 2023' 'February 2023' 'January 2023'
 'December 2022' 'November 2022' 'October 2022' 'September 2022'
 'August 2022' 'July 2022' 'June 2022' 'May 2022' 'April 2022'
 'March 2022' 'February 2022' 'January 2022']

Valores únicos na coluna 'year':
 [2025 2024 2023 2022]

Valores únicos na coluna 'month':
 ['January' 'March' 'February' 'October' 'December' 'November' 'September'
 'August' 'July' 'June' 'May' 'April']

Valores únicos na coluna 'score':
 [10.   9.   8.   1.   7.   6.   5.   2.   4.   3.   7.9  4.6  7.5]

Valores únicos na coluna 'title_review':
 ['Exceptional' 'Well placed hotel with great facilities'
 'Very clean with professional staff and very good facilities. Extremely recommended.'
 ...
 'fruhstuck: espresso, schwarzbrot, aqua minerale con gas....nicht angeboten, trotz nachfrage nicht moglich. personal freund'
 'Habitacion bien. edificio y zonas comunes muy desfasadas, necesita puesta al dia'
 'razoavel']

Valores únicos na coluna 'title_review_en':
 ['Exceptional' 'Well placed hotel with great facilities'
 'Very clean with professional staff and very good facilities. Extremely recommended.'
 ...
 'Breakfast: espresso, black bread, aqua minerals con gas ... not offered, despite demand. staff friend'
 'ROOM WELL. very outdated building and areas, you need up to date'
 'reasonable']

Valores únicos na coluna 'pos_review':
 ['Room was spacious, clean and with good amenities'
 "In good location for exploring Porto... approx 20 minute walk down to river .  Clean , comfortable & good variety at breakfast  Bonus having a restaurant on 17th floor ... I didn't eat there but had drinks ... good service & great views"
 'Staff is very friendly and extremely professional and always willing to help.'
 ... 'la disponibilite du personnel'
 'A vista, a boa apresentacao do hotel, o pequeno almoco com imensa variedade'
 "cet etablissement est tres bien situe. A proximite des places marchandes, menant directement au centre de la ville. La chambre etait propre, au calme et spacieuse. Les membres du personnel sont tous accueillants, a l'ecoute et agreables. Le restaurant et le bar au derniere etage est reellement a faire, car la vue y est incroyable."]

Valores únicos na coluna 'pos_review_en':
 ['Room was spacious, clean and with good amenities'
 "In good location for exploring Porto... approx 20 minute walk down to river .  Clean , comfortable & good variety at breakfast  Bonus having a restaurant on 17th floor ... I didn't eat there but had drinks ... good service & great views"
 'Staff is very friendly and extremely professional and always willing to help.'
 ... 'personnel availability'
 'The view, the good presentation of the hotel, the breakfast with immense variety'
 'This establishment is very well located. Near merchant squares, leading directly to the center of the city. The room was clean, quiet and spacious. The staff members are all welcoming, attentive and pleasant. The restaurant and the bar on the last floor is really to be done, because the view is incredible.']

Valores únicos na coluna 'neg_review':
 ['No review' "Can't think of any improvement" 'Nothing' ...
 "l'austerite du batiment exterieur" 'l eloignement du centre de la ville'
 'a televisao nao funcionava bem']

Valores únicos na coluna 'neg_review_en':
 ['No review' "Can't think of any improvement" 'Nothing' ...
 'The austerity of the outdoor building'
 'The distance from the center of the city' "Television didn't work well"]

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5037 entries, 0 to 5036
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             5037 non-null   object
 1   country          5037 non-null   object
 2   room_type        5037 non-null   object
 3   traveler_type    5037 non-null   object
 4   nr_nights        5037 non-null   int64
 5   date             5037 non-null   object
 6   year             5037 non-null   int64
 7   month            5037 non-null   object
 8   score            5037 non-null   float64
 9   title_review     5032 non-null   object
 10  title_review_en  5031 non-null   object
 11  pos_review       5037 non-null   object
 12  pos_review_en    5037 non-null   object
 13  neg_review       5037 non-null   object
 14  neg_review_en    5037 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 590.4+ KB

In [22]:
df.head()

,name,country,room_type,traveler_type,nr_nights,date,year,month,score,title_review,title_review_en,pos_review,pos_review_en,neg_review,neg_review_en
0,Christina,Belgium,Comfort Double Room,Family,3,January 2025,2025,January,10.0,Exceptional,Exceptional,"Room was spacious, clean and with good amenities","Room was spacious, clean and with good amenities",No review,No review
1,Helen,United Kingdom,Comfort Single Room,Solo traveller,2,March 2025,2025,March,9.0,Well placed hotel with great facilities,Well placed hotel with great facilities,In good location for exploring Porto... approx...,In good location for exploring Porto... approx...,Can't think of any improvement,Can't think of any improvement
2,Irene,United Kingdom,Comfort King Room,Couple,2,March 2025,2025,March,9.0,Very clean with professional staff and very go...,Very clean with professional staff and very go...,Staff is very friendly and extremely professio...,Staff is very friendly and extremely professio...,Nothing,Nothing
3,Andrea,Hungary,Plus Comfort Suite,Family,4,February 2025,2025,February,9.0,"Elegant, good hotel in the center","Elegant, good hotel in the center",We really liked the hotel and the suit. From o...,We really liked the hotel and the suit. From o...,"In the smaller room there is no socket, you ca...","In the smaller room there is no socket, you ca..."
4,Anjali,Canada,Comfort Family Room,Family,2,February 2025,2025,February,8.0,Good location and nice hotel with spacious units.,Good location and nice hotel with spacious units.,Location and size of the unit. Comfortable for...,Location and size of the unit. Comfortable for...,No review,No review

In [28]:
col_keep = [
    'country', 'room_type', 'traveler_type', 'nr_nights', 'date', 'year', 'month', 'score',
    'title_review_en', 'pos_review_en', 'neg_review_en']
df = df[col_keep]
df.head(2)

,country,room_type,traveler_type,nr_nights,date,year,month,score,title_review_en,pos_review_en,neg_review_en
0,Belgium,Comfort Double Room,Family,3,January 2025,2025,January,10.0,Exceptional,"Room was spacious, clean and with good amenities",No review
1,United Kingdom,Comfort Single Room,Solo traveller,2,March 2025,2025,March,9.0,Well placed hotel with great facilities,In good location for exploring Porto... approx...,Can't think of any improvement

In [33]:
# Saves the dataframes to .csv and .xlsx
df.to_excel("reviews_clean.xlsx", index=False, encoding="utf-8")
df.to_csv("reviews_clean_csv.csv", index=False, encoding="utf-8")

Vamos meter o mês em número!

# Ideias sugestões professor 
Marketing: qual é o niche que queremos atacar
Análise de niche
Fazer a análise dos comentários em separado - não juntar os comentários num texto único
Fazer a análise dos verdadeiros negativos vs verdadeiros positivos : fazer modelos (?)