In [3]:
#!pip install nltk
#!pip install gensim
#!pip install pyLDAvis==2.1.2
#!pip install scikit-learn
!pip install gensim

Defaulting to user installation because normal site-packages is not writeable
Collecting gensim
  Using cached gensim-4.3.3.tar.gz (23.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): still running...
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Using cached scipy-1.13.1.tar.gz (57.2 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [47 lines of output]
  + meson setup C:\Users\Hp\AppData\Local\Temp\pip-install-2yg8sbnz\scipy_47ee3829b0214ad0802693792e648b59 C:\Users\Hp\AppData\Local\Temp\pip-install-2yg8sbnz\scipy_47ee3829b0214ad0802693792e648b59\.mesonpy-g2ph6io6 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Hp\AppData\Local\Temp\pip-install-2yg8sbnz\scipy_47ee3829b0214ad0802693792e648b59\.mesonpy-g2ph6io6\meson-python-native-file.ini
  The Meson build system
  Version: 1.7.0
  Source dir: C:\Users\Hp\AppData\Local\Temp\pip-install-2yg8sbnz\scipy_47ee3829b0214ad0802693792e648b59
  Build dir: C:\Users\Hp\AppData\Local\Temp\pip-install-2yg8sbnz\scipy_47ee3829b0214ad0802693792e648b59\.mesonpy-g2ph6io6
  Build type: native build
  Project name: scipy
  Project version: 1.13.1
  Activating VS 16.11.43
  C compiler for the host machine: cl (msvc 19.29.30158 "Microsoft (R) C/C++ Optimizing Compiler VersÆo 19.29.30158 para x64")
  C linker for the host machine: link link 14.29.30158.0
  C++ compiler for the host machine: cl (msvc 19.29.30158 "Microsoft (R) C/C++ Optimizing Compiler VersÆo 19.29.30158 para x64")
  C++ linker for the host machine: link link 14.29.30158.0
  Cython compiler for the host machine: cython (cython 3.0.12)
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (C:\Python313\python.exe)
  Run-time dependency python found: YES 3.13
  Program cython found: YES (C:\Users\Hp\AppData\Local\Temp\pip-build-env-9qww4tk6\overlay\Scripts\cython.EXE)
  Compiler for C supports arguments -Wno-unused-but-set-variable: NO
  Compiler for C supports arguments -Wno-unused-function: NO
  Compiler for C supports arguments -Wno-conversion: NO
  Compiler for C supports arguments -Wno-misleading-indentation: NO
  Library m found: NO

  ..\meson.build:78:0: ERROR: Unknown compiler(s): [['ifort'], ['gfortran'], ['flang-new'], ['flang'], ['pgfortran'], ['g95']]
  The following exception(s) were encountered:
  Running `ifort --help` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `ifort --version` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `ifort -V` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `gfortran --help` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `gfortran --version` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `gfortran -V` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `flang-new --help` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `flang-new --version` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `flang-new -V` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `flang --help` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `flang --version` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `flang -V` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `pgfortran --help` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `pgfortran --version` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `pgfortran -V` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `g95 --help` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `g95 --version` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"
  Running `g95 -V` gave "[WinError 2] O sistema não conseguiu localizar o ficheiro especificado"

  A full log can be found at C:\Users\Hp\AppData\Local\Temp\pip-install-2yg8sbnz\scipy_47ee3829b0214ad0802693792e648b59\.mesonpy-g2ph6io6\meson-logs\meson-log.txt
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [102]:
import pandas as pd
import numpy as np
import nltk
import nltk.corpus
import nltk.sentiment
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
from nltk.corpus import stopwords

nltk.download('omw-1.4')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('punkt_tab')
import os

import re
import string
from string import punctuation

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score


#import gensim
#from gensim import corpora

import pyLDAvis
import pyLDAvis.gensim

[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [103]:
df = pd.read_csv("cleandata.csv")
df.head()

,country,room_type,traveler_type,nr_nights,year,month,score,title_review_en,pos_review_en,neg_review_en
0,belgium,comfort double room,family,3,2025,1,10.0,exceptional,"room was spacious, clean and with good amenities",no review
1,united kingdom,comfort single room,solo traveller,2,2025,3,9.0,well placed hotel with great facilities,in good location for exploring porto... approx...,can't think of any improvement
2,united kingdom,comfort king room,couple,2,2025,3,9.0,very clean with professional staff and very go...,staff is very friendly and extremely professio...,nothing
3,hungary,plus comfort suite,family,4,2025,2,9.0,"elegant, good hotel in the center",we really liked the hotel and the suit. from o...,"in the smaller room there is no socket, you ca..."
4,canada,comfort family room,family,2,2025,2,8.0,good location and nice hotel with spacious units.,location and size of the unit. comfortable for...,no review

In [104]:
#for i in df["score"]:
    #if i >= 5:
    #    df['Sentiment']="POS"
    #else:
    #    df['Sentiment']="NEG"

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5037 entries, 0 to 5036
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          5037 non-null   object
 1   room_type        5037 non-null   object
 2   traveler_type    5037 non-null   object
 3   nr_nights        5037 non-null   int64
 4   year             5037 non-null   int64
 5   month            5037 non-null   int64
 6   score            5037 non-null   float64
 7   title_review_en  5031 non-null   object
 8   pos_review_en    5036 non-null   object
 9   neg_review_en    5031 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 393.6+ KB

In [106]:
df['title_review_en'] = df['title_review_en'].astype(str)

In [107]:
df['Token'] = df['title_review_en'].apply(lambda x: word_tokenize(x.lower()))
df

,country,room_type,traveler_type,nr_nights,year,month,score,title_review_en,pos_review_en,neg_review_en,Token
0,belgium,comfort double room,family,3,2025,1,10.0,exceptional,"room was spacious, clean and with good amenities",no review,[exceptional]
1,united kingdom,comfort single room,solo traveller,2,2025,3,9.0,well placed hotel with great facilities,in good location for exploring porto... approx...,can't think of any improvement,"[well, placed, hotel, with, great, facilities]"
2,united kingdom,comfort king room,couple,2,2025,3,9.0,very clean with professional staff and very go...,staff is very friendly and extremely professio...,nothing,"[very, clean, with, professional, staff, and, ..."
3,hungary,plus comfort suite,family,4,2025,2,9.0,"elegant, good hotel in the center",we really liked the hotel and the suit. from o...,"in the smaller room there is no socket, you ca...","[elegant, ,, good, hotel, in, the, center]"
4,canada,comfort family room,family,2,2025,2,8.0,good location and nice hotel with spacious units.,location and size of the unit. comfortable for...,no review,"[good, location, and, nice, hotel, with, spaci..."
...,...,...,...,...,...,...,...,...,...,...,...
5032,switzerland,comfort double room,couple,2,2023,6,7.0,good,no review,no review,[good]
5033,czech republic,comfort twin room,solo traveller,2,2022,9,7.0,good,no review,no review,[good]
5034,portugal,comfort double room,couple,1,2022,8,6.0,pleasant,no review,no review,[pleasant]
5035,chile,comfort twin room,family,2,2022,7,6.0,pleasant,no review,no review,[pleasant]
5036,spain,comfort double room,family,1,2022,2,6.0,pleasant,no review,no review,[pleasant]

In [108]:
stopwords = stopwords.words('english')
punctuation = list(punctuation)
words = set(nltk.corpus.words.words())   
df['Token'] = df['Token'].apply(lambda x: [t for t in x if t not in stopwords and t not in punctuation and t in words])
df

,country,room_type,traveler_type,nr_nights,year,month,score,title_review_en,pos_review_en,neg_review_en,Token
0,belgium,comfort double room,family,3,2025,1,10.0,exceptional,"room was spacious, clean and with good amenities",no review,[exceptional]
1,united kingdom,comfort single room,solo traveller,2,2025,3,9.0,well placed hotel with great facilities,in good location for exploring porto... approx...,can't think of any improvement,"[well, hotel, great]"
2,united kingdom,comfort king room,couple,2,2025,3,9.0,very clean with professional staff and very go...,staff is very friendly and extremely professio...,nothing,"[clean, professional, staff, good, extremely]"
3,hungary,plus comfort suite,family,4,2025,2,9.0,"elegant, good hotel in the center",we really liked the hotel and the suit. from o...,"in the smaller room there is no socket, you ca...","[elegant, good, hotel, center]"
4,canada,comfort family room,family,2,2025,2,8.0,good location and nice hotel with spacious units.,location and size of the unit. comfortable for...,no review,"[good, location, nice, hotel, spacious]"
...,...,...,...,...,...,...,...,...,...,...,...
5032,switzerland,comfort double room,couple,2,2023,6,7.0,good,no review,no review,[good]
5033,czech republic,comfort twin room,solo traveller,2,2022,9,7.0,good,no review,no review,[good]
5034,portugal,comfort double room,couple,1,2022,8,6.0,pleasant,no review,no review,[pleasant]
5035,chile,comfort twin room,family,2,2022,7,6.0,pleasant,no review,no review,[pleasant]
5036,spain,comfort double room,family,1,2022,2,6.0,pleasant,no review,no review,[pleasant]

In [109]:
df['freqdist'] = df['Token'].apply(lambda x: FreqDist(x))
df

,country,room_type,traveler_type,nr_nights,year,month,score,title_review_en,pos_review_en,neg_review_en,Token,freqdist
0,belgium,comfort double room,family,3,2025,1,10.0,exceptional,"room was spacious, clean and with good amenities",no review,[exceptional],{'exceptional': 1}
1,united kingdom,comfort single room,solo traveller,2,2025,3,9.0,well placed hotel with great facilities,in good location for exploring porto... approx...,can't think of any improvement,"[well, hotel, great]","{'well': 1, 'hotel': 1, 'great': 1}"
2,united kingdom,comfort king room,couple,2,2025,3,9.0,very clean with professional staff and very go...,staff is very friendly and extremely professio...,nothing,"[clean, professional, staff, good, extremely]","{'clean': 1, 'professional': 1, 'staff': 1, 'g..."
3,hungary,plus comfort suite,family,4,2025,2,9.0,"elegant, good hotel in the center",we really liked the hotel and the suit. from o...,"in the smaller room there is no socket, you ca...","[elegant, good, hotel, center]","{'elegant': 1, 'good': 1, 'hotel': 1, 'center'..."
4,canada,comfort family room,family,2,2025,2,8.0,good location and nice hotel with spacious units.,location and size of the unit. comfortable for...,no review,"[good, location, nice, hotel, spacious]","{'good': 1, 'location': 1, 'nice': 1, 'hotel':..."
...,...,...,...,...,...,...,...,...,...,...,...,...
5032,switzerland,comfort double room,couple,2,2023,6,7.0,good,no review,no review,[good],{'good': 1}
5033,czech republic,comfort twin room,solo traveller,2,2022,9,7.0,good,no review,no review,[good],{'good': 1}
5034,portugal,comfort double room,couple,1,2022,8,6.0,pleasant,no review,no review,[pleasant],{'pleasant': 1}
5035,chile,comfort twin room,family,2,2022,7,6.0,pleasant,no review,no review,[pleasant],{'pleasant': 1}
5036,spain,comfort double room,family,1,2022,2,6.0,pleasant,no review,no review,[pleasant],{'pleasant': 1}

In [110]:
#create a function that applies the stemming task
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text])
df["Token"] = df["Token"].apply(lambda x: stem_words(x))

In [96]:
#create a function that applies the lemmatizer task
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text])
df["Token"] = df["Token"].apply(lambda text: lemmatize_words(text))

In [111]:
df['Token']

0                                   except
1                         well hotel great
2       clean profession staff good extrem
3                   eleg good hotel center
4            good locat nice hotel spaciou
                       ...
5032                                  good
5033                                  good
5034                              pleasant
5035                              pleasant
5036                              pleasant
Name: Token, Length: 5037, dtype: object

In [112]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df.Token)
df_bow_sklearn = pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
df_bow_sklearn

,absolut,accept,access,accommod,accord,account,across,actual,ad,address,...,wo,wonder,work,wors,worth,worthi,would,wrong,yang,year
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5032,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5033,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5034,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5035,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5036,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [113]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(df.Token)
df_bow_sklearn = pd.DataFrame(X.toarray(),columns=tfidf_vectorizer.get_feature_names_out())
df_bow_sklearn

,absolut,accept,access,accommod,accord,account,across,actual,ad,address,...,wo,wonder,work,wors,worth,worthi,would,wrong,yang,year
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5032,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5034,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5036,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [114]:
from sklearn.feature_extraction.text import CountVectorizer
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
X = bigram_vectorizer.fit_transform(df.Token)
df_bow_sklearn = pd.DataFrame(X.toarray(),columns=bigram_vectorizer.get_feature_names_out())
df_bow_sklearn

,absolut bar,absolut fantast,absolut love,absolut mind,accept hotel,access difficult,access foot,access hotel,accommod advis,accommod good,...,would recommend,would repeat,would return,would stay,would stop,would take,would thoroughli,would total,would undoubtedli,yang jing
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5032,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5033,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5034,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5035,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5036,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
#df_bow_sklearn['Sentiment']=df['Sentiment']

In [50]:
X = df_bow_sklearn.loc[:, df_bow_sklearn.columns != 'Sentiment']
y = df_bow_sklearn.loc[:, df_bow_sklearn.columns == 'Sentiment']

In [52]:
clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, y, cv=5)
print(scores.mean())

clf = RandomForestClassifier(n_estimators=10, random_state=0)
scores = cross_val_score(clf, X, y, cv=5)
print(scores.mean())

ValueError: at least one array or dtype is required

In [119]:
import nltk

sid_obj = nltk.sentiment.vader.SentimentIntensityAnalyzer()
for i in range(df.shape[0]):
    sentiment_dict = sid_obj.polarity_scores(df.title_review_en[i])
    print(sentiment_dict)
    if i == 100:
        break

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.392, 'pos': 0.608, 'compound': 0.7351}
{'neg': 0.0, 'neu': 0.491, 'pos': 0.509, 'compound': 0.8063}
{'neg': 0.0, 'neu': 0.4, 'pos': 0.6, 'compound': 0.7184}
{'neg': 0.0, 'neu': 0.513, 'pos': 0.487, 'compound': 0.6908}
{'neg': 0.0, 'neu': 0.519, 'pos': 0.481, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.424, 'pos': 0.576, 'compound': 0.7783}
{'neg': 0.0, 'neu': 0.3, 'pos': 0.7, 'compound': 0.7906}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.484, 'pos': 0.516, 'compound': 0.4927}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.581, 'pos': 0.419, 'compound': 0.7579}
{'neg': 0.0, 'neu': 0.229, 'pos': 0.771, 'compound': 0.5229}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.213, 'pos': 0.787, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.213, 'pos': 0.787, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.539, 'pos': 0.461, 'compound': 0.63}
{'neg': 0.0, 'neu': 0.603, 'pos': 0.397, 'compound': 0.8718}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.619, 'pos': 0.381, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 0.185, 'pos': 0.815, 'compound': 0.6588}
{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'compound': 0.8268}
{'neg': 0.0, 'neu': 0.213, 'pos': 0.787, 'compound': 0.5719}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.69, 'pos': 0.31, 'compound': 0.4019}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.218, 'pos': 0.782, 'compound': 0.5563}
{'neg': 0.0, 'neu': 0.566, 'pos': 0.434, 'compound': 0.3182}
{'neg': 0.133, 'neu': 0.663, 'pos': 0.204, 'compound': 0.3182}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.417, 'pos': 0.583, 'compound': 0.7906}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.709, 'pos': 0.291, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.42, 'pos': 0.58, 'compound': 0.7841}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.643, 'pos': 0.357, 'compound': 0.6115}
{'neg': 0.0, 'neu': 0.519, 'pos': 0.481, 'compound': 0.5719}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.433, 'pos': 0.567, 'compound': 0.9153}
{'neg': 0.0, 'neu': 0.655, 'pos': 0.345, 'compound': 0.7003}
{'neg': 0.0, 'neu': 0.519, 'pos': 0.481, 'compound': 0.5719}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'compound': 0.91}
{'neg': 0.325, 'neu': 0.675, 'pos': 0.0, 'compound': -0.5216}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.688, 'pos': 0.312, 'compound': 0.2057}
{'neg': 0.0, 'neu': 0.357, 'pos': 0.643, 'compound': 0.2023}
{'neg': 0.0, 'neu': 0.279, 'pos': 0.721, 'compound': 0.8293}
{'neg': 0.0, 'neu': 0.422, 'pos': 0.578, 'compound': 0.9287}
{'neg': 0.0, 'neu': 0.379, 'pos': 0.621, 'compound': 0.8481}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.678, 'pos': 0.322, 'compound': 0.5859}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.644, 'pos': 0.356, 'compound': 0.8074}
{'neg': 0.0, 'neu': 0.633, 'pos': 0.367, 'compound': 0.4404}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.213, 'pos': 0.787, 'compound': 0.5719}
{'neg': 0.0, 'neu': 0.3, 'pos': 0.7, 'compound': 0.7906}
{'neg': 0.0, 'neu': 0.423, 'pos': 0.577, 'compound': 0.6249}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 0.218, 'pos': 0.782, 'compound': 0.5563}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.238, 'pos': 0.762, 'compound': 0.4927}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.256, 'pos': 0.744, 'compound': 0.4404}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.4926}
{'neg': 0.0, 'neu': 0.564, 'pos': 0.436, 'compound': 0.4754}
{'neg': 0.0, 'neu': 0.834, 'pos': 0.166, 'compound': 0.4576}
{'neg': 0.0, 'neu': 0.372, 'pos': 0.628, 'compound': 0.7759}
{'neg': 0.0, 'neu': 0.439, 'pos': 0.561, 'compound': 0.7496}
{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6249}
{'neg': 0.0, 'neu': 0.84, 'pos': 0.16, 'compound': 0.2263}
{'neg': 0.0, 'neu': 0.309, 'pos': 0.691, 'compound': 0.7717}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.371, 'pos': 0.629, 'compound': 0.7778}
{'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'compound': 0.8271}